### ISSUE TITLE
Decide on CI/CD Pipeline and Deployment Platform 

### ISSUE THREAD

**Issue by vburmus** [pwr-thesis/fleet-assistant#11]
Evaluate and choose appropriate continuous integration/continuous deployment (CI/CD) tools and platforms where the Fleet Management application will be deployed. The decision should consider ease of integration with the current tech stack and **cost efficiency**. 
Cloud services used:
- VMs
- DB(SQL)
- OpenAI API (check how many tokens, etc.)

**Comment by vburmus** [comment]
Suggesting Azure, as we have plenty opportunities with it (Free tier + 100$ student credit). I've checked OpenAPI endpoint creation, and it is very simple, contains ready-to-use code to integrate to our app.
![Image](https://github.com/user-attachments/assets/a6ca48d8-0900-4d20-946b-95498119cf6c)

**Comment by vburmus** [comment]
I've applied our team for 300$ AWS credit

**Comment by troshchylo** [comment]
As we have not received 300$ from AWS yet, we will deploy our application using Free Tier of different cloud Providers.
For the OpenAI API we will use Azure Cloud, as it provides us with 100$ free credits for students.
All other services will be deployed on AWS Cloud because it has wide range of Free Tier services.

Table of used services:
| Component | Cloud | Service name | Available usage |
| --- | --- | --- | --- |
| OpenAI API | Azure | OpenAI Service | 100$ for students |
| DB (SQL) | AWS | RDS for Postgres | 750 hours + 20 GB / monthly |
| Virtual Machine | AWS | EC2 | 750 hours / monthly |

We've decided to move forward with multi-cloud options because Azure offers lower free usage volume on other services, and we won't be able to put in the budget for the project.

**Comment by maryushp** [comment]
Provide GitHub page documentation for decided cloud solution.

**Comment by troshchylo** [comment]
https://github.com/pwr-thesis/fleet-assistant/wiki/System-Architecture#deployment-architecture
